version: '2.4'
services:
  nginx:
    container_name: nginx-loc
    image: nginx:latest
    restart: always
    volumes:
      - ../src/main/resources/nginx/conf/local:/etc/nginx/conf.d
    ports:
      - "80:80"
